# Generated by Django 6.0.6 on 2026-06-15 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(db_column='acao', max_length=100)),
            ],
            options={
                'db_table': 'acoes_manutencao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=100)),
                ('funcao', models.CharField(db_column='funcao', max_length=50)),
                ('status', models.CharField(db_column='status', max_length=20)),
            ],
            options={
                'db_table': 'colaboradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPorMolde',
            fields=[
                ('id_item', models.AutoField(db_column='id_item', primary_key=True, serialize=False)),
                ('item_codigo', models.CharField(db_column='item_codigo', max_length=50)),
                ('descricao', models.CharField(db_column='descricao', max_length=100)),
                ('cod_complementar', models.CharField(blank=True, db_column='cod_complementar', max_length=50, null=True)),
                ('linha', models.CharField(blank=True, db_column='linha', max_length=50, null=True)),
                ('status', models.CharField(db_column='status', default='Ativo', max_length=20)),
            ],
            options={
                'db_table': 'itens_por_molde',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.AutoField(db_column='id_maquina', primary_key=True, serialize=False)),
                ('maquina', models.CharField(db_column='maquina', max_length=50)),
                ('grupo_maquina', models.CharField(db_column='grupo_maquina', max_length=50)),
                ('descricao', models.CharField(db_column='descricao', max_length=100)),
                ('status', models.CharField(db_column='status', max_length=20)),
            ],
            options={
                'db_table': 'maquinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Molde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molde_nome', models.CharField(db_column='molde_nome', max_length=100)),
                ('endereco_molde', models.CharField(db_column='endereco_molde', max_length=50)),
                ('status', models.CharField(db_column='status', max_length=20)),
            ],
            options={
                'db_table': 'moldes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(db_column='problema', max_length=100)),
                ('descricao', models.CharField(db_column='descricao', max_length=200)),
            ],
            options={
                'db_table': 'problemas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'solicitacao_acoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_manutencao', models.CharField(blank=True, db_column='ordem_manutencao', max_length=50, null=True)),
                ('ordem_producao', models.CharField(blank=True, db_column='ordem_producao', max_length=50, null=True)),
                ('parecer_producao', models.TextField(db_column='parecer_producao')),
                ('parecer_ferramentaria', models.TextField(db_column='parecer_ferramentaria', null=True)),
                ('status', models.CharField(db_column='status', default='Aberto', max_length=20)),
                ('data_op', models.DateTimeField(blank=True, db_column='data_op', null=True)),
                ('data_abertura', models.DateTimeField(db_column='data_abertura', default=django.utils.timezone.now)),
                ('data_fechamento', models.DateTimeField(db_column='data_fechamento', null=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True, db_column='ultima_alteracao')),
            ],
            options={
                'db_table': 'solicitacoes_manutencao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'solicitacao_problemas',
                'managed': False,
            },
        ),
    ]
