# Generated by Django 6.0.6 on 2026-06-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ferramentaria', '0002_logauditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaomanutencao',
            options={'managed': True},
        ),
    ]
