# Generated by Django 6.0.6 on 2026-06-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ferramentaria', '0003_alter_solicitacaomanutencao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='acoes',
            field=models.ManyToManyField(through='app_ferramentaria.SolicitacaoAcao', to='app_ferramentaria.acaomanutencao'),
        ),
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ferramentaria.itempormolde', verbose_name='Item / IN'),
        ),
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='maquina',
            field=models.ForeignKey(blank=True, db_column='id_maquina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_ferramentaria.maquina'),
        ),
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='molde',
            field=models.ForeignKey(db_column='id_molde', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_ferramentaria.molde'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='operador',
            field=models.ForeignKey(db_column='id_operador', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='abertas_por', to='app_ferramentaria.colaborador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='problemas',
            field=models.ManyToManyField(through='app_ferramentaria.SolicitacaoProblema', to='app_ferramentaria.problema'),
        ),
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='responsavel',
            field=models.ForeignKey(db_column='id_responsavel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resolvidas_por', to='app_ferramentaria.colaborador'),
        ),
    ]
