# Generated by Django 6.0.6 on 2026-06-24 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ferramentaria', '0004_solicitacaomanutencao_acoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='motivo_manutencao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo (Em Manutenção)'),
        ),
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='previsao_retorno',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Retorno'),
        ),
        migrations.AlterField(
            model_name='solicitacaomanutencao',
            name='molde',
            field=models.ForeignKey(blank=True, db_column='id_molde', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_ferramentaria.molde'),
        ),
        migrations.AlterField(
            model_name='solicitacaomanutencao',
            name='operador',
            field=models.ForeignKey(blank=True, db_column='id_operador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='abertas_por', to='app_ferramentaria.colaborador'),
        ),
    ]
