# Generated by Django 6.0.6 on 2026-06-24 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ferramentaria', '0005_solicitacaomanutencao_motivo_manutencao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaomanutencao',
            name='maquina',
            field=models.ForeignKey(db_column='id_maquina', on_delete=django.db.models.deletion.DO_NOTHING, to='app_ferramentaria.maquina'),
        ),
        migrations.AlterField(
            model_name='solicitacaomanutencao',
            name='molde',
            field=models.ForeignKey(db_column='id_molde', on_delete=django.db.models.deletion.DO_NOTHING, to='app_ferramentaria.molde'),
        ),
        migrations.AlterField(
            model_name='solicitacaomanutencao',
            name='operador',
            field=models.ForeignKey(db_column='id_operador', on_delete=django.db.models.deletion.DO_NOTHING, related_name='abertas_por', to='app_ferramentaria.colaborador'),
        ),
    ]
