# Generated by Django 6.0.6 on 2026-06-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ferramentaria', '0006_alter_solicitacaomanutencao_maquina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='modulo',
            field=models.CharField(default='GERAL', max_length=50, verbose_name='Módulo'),
        ),
    ]
