# Generated by Django 6.0.6 on 2026-07-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ferramentaria', '0007_logauditoria_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='ciclo_momento',
            field=models.IntegerField(default=0, verbose_name='Ciclos do Molde na Abertura da OS'),
        ),
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='ultima_contagem',
            field=models.IntegerField(default=0, verbose_name='Última Contagem de Peças Produzidas'),
        ),
    ]
