# Generated by Django 6.0.6 on 2026-07-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ferramentaria', '0008_solicitacaomanutencao_ciclo_momento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaomanutencao',
            options={'managed': False},
        ),
    ]
